### ISSUE TITLE
Ver 0.0.3 - java.lang.NullPointerException - (DocumentLifeCycleHandler.java:157)

### ISSUE THREAD

**Issue by suiwenfeng** [gorkem/vscode-java#40] opened 2016-09-26 12:04 UTC
```
[Error] 2016-9-26 19:46:10 Exception on incoming message dispatcher
null
java.lang.NullPointerException
	at org.jboss.tools.vscode.java.handlers.DocumentLifeCycleHandler.handleChanged(DocumentLifeCycleHandler.java:157)
	at org.jboss.tools.vscode.java.handlers.DocumentLifeCycleHandler.access$2(DocumentLifeCycleHandler.java:154)
	at org.jboss.tools.vscode.java.handlers.DocumentLifeCycleHandler$ChangeHandler$1.run(DocumentLifeCycleHandler.java:98)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2240)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2262)
	at org.jboss.tools.vscode.java.handlers.DocumentLifeCycleHandler$ChangeHandler.handle(DocumentLifeCycleHandler.java:95)
	at org.jboss.tools.vscode.java.handlers.DocumentLifeCycleHandler$ChangeHandler.handle(DocumentLifeCycleHandler.java:1)
	at org.jboss.tools.langs.base.LSPServer.dispatchNotification(LSPServer.java:222)
	at org.jboss.tools.langs.base.LSPServer.messageReceived(LSPServer.java:156)
	at org.jboss.tools.langs.transport.AbstractConnection$DispatcherThread.run(AbstractConnection.java:32)
```

Above is the full error log, and i am using Window 10. That`s all.

In addition, i cannot see the thumbs up.

**Comment by fbricon** [comment] 2016-09-26 13:12
Closing as duplicate of #34. There should be a release with the fix later today.

**Closed by fbricon** 2016-09-26 13:12 UTC
Labels: duplicate
