### ISSUE TITLE
Getting Error AM Exception on incoming message dispatcher

### ISSUE THREAD

**Issue by ianrobrien** [gorkem/vscode-java#33] opened 2016-09-22 14:35 UTC
Everytime I type anything into the editor I get the following error in my Ouput log:

> [Error] Sep 22, 2016 10:32:13 AM Exception on incoming message dispatcher
null
java.lang.NullPointerException
	at org.jboss.tools.vscode.java.handlers.DocumentLifeCycleHandler.handleChanged(DocumentLifeCycleHandler.java:157)
	at org.jboss.tools.vscode.java.handlers.DocumentLifeCycleHandler.access$2(DocumentLifeCycleHandler.java:154)
	at org.jboss.tools.vscode.java.handlers.DocumentLifeCycleHandler$ChangeHandler$1.run(DocumentLifeCycleHandler.java:98)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2240)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2262)
	at org.jboss.tools.vscode.java.handlers.DocumentLifeCycleHandler$ChangeHandler.handle(DocumentLifeCycleHandler.java:95)
	at org.jboss.tools.vscode.java.handlers.DocumentLifeCycleHandler$ChangeHandler.handle(DocumentLifeCycleHandler.java:1)
	at org.jboss.tools.langs.base.LSPServer.dispatchNotification(LSPServer.java:222)
	at org.jboss.tools.langs.base.LSPServer.messageReceived(LSPServer.java:156)
	at org.jboss.tools.langs.transport.AbstractConnection$DispatcherThread.run(AbstractConnection.java:32)

OS: Windows 7 Enterprise x64 SP1
Visual Code Version: 1.5.2
JDK Version: 1.8.102 (Oracle)
Language Support version: 0.0.3

**Comment by fbricon** [comment] 2016-09-22 16:27
Closing as duplicate of #34

**Closed by fbricon** 2016-09-22 16:27 UTC
